GET http://localhost:3000/api/workshops HTTP/1.1

GET http://localhost:3000/api/workshops?slug=one HTTP/1.1

GET http://localhost:3000/api/workshops/5f11d5dce023403f706e1583 HTTP/1.1

POST http://localhost:3000/api/workshops HTTP/1.1
content-type: application/json
authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZib2xjaWNAdHZ6LmhyIiwidXNlcklkIjoiNWYwYWRkZjI1NzVjNTk0NTg0NTNlNTRiIiwiaWF0IjoxNTk1MDA2MTYzLCJleHAiOjE1OTUwMDk3NjN9.XCJk0-q06rEi5p0W9MBhoU2BRFzsjO49nWE2bIXwUo0

{
    "title": "Who's still afraid of fear? A workshop about anxiety.",
    "summary": "A long, long time ago, our ancestors were in constant danger. In this environment an adaptive emotion evolved, that allowed them to forsee and react to threats - anxiety. Even though nowdays we rarely find ourselves in mortal danger, we are \"stuck\" with an excitable mind that is quickly overwhelmed by fear. Today anxiety is recognized as a leading psychological disorder. In this workshop we will learn about the nature of this disorder and how to prevent it.",
    "address": "Savjetovalište TVZ, Vrbik 8, 10000 Zagreb",
    "dateTime": "2020-07-17T16:43:04.367Z",
    "slug": "who-is-still-afraid-of-fear"
}

DELETE http://localhost:3000/api/workshops/5f11d5dce023403f706e1583 HTTP/1.1
authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZib2xjaWNAdHZ6LmhyIiwidXNlcklkIjoiNWYwYWRkZjI1NzVjNTk0NTg0NTNlNTRiIiwiaWF0IjoxNTk1MDA2MTYzLCJleHAiOjE1OTUwMDk3NjN9.XCJk0-q06rEi5p0W9MBhoU2BRFzsjO49nWE2bIXwUo0
